CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20) PRIMARY KEY
);

CREATE TABLE BOARD(
    BOARD_NUM NUMBER CONSTRAINT PK_BNUM PRIMARY KEY,
    BOARD_WRITER VARCHAR2(20),
    BOARD_TITLE VARCHAR2(50) CONSTRAINT NN_BTIBLE NOT NULL,
    BOARD_CONTENT VARCHAR2(2000) CONSTRAINT NN_BCONTENT NOT NULL,
    BOARD_ORIGINAL_FILENAME VARCHAR2(100),
    BOARD_RENAME_FILENAME VARCHAR2(100),
    BOARD_REPLY_REF NUMBER DEFAULT 1,
    BOARD_REPLY_LEV NUMBER DEFAULT 1,
    BOARD_REPLY_SEQ NUMBER DEFAULT 1,
    BOARD_READCOUNT NUMBER DEFAULT 0,
    BOARD_DATE DATE DEFAULT SYSDATE CONSTRAINT NN_BDATE NOT NULL,
    CONSTRAINT FK_BWRITER FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER
);
DROP TABLE BOARD;
SELECT * FROM BOARD;
COMMENT ON COLUMN BOARD.BOARD_NUM IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자아이디';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_ORIGINAL_FILENAME IS '원본첨부파일명';
COMMENT ON COLUMN BOARD.BOARD_RENAME_FILENAME IS '바뀐첨부파일명';
COMMENT ON COLUMN BOARD.BOARD_REPLY_REF IS '원글번호';
COMMENT ON COLUMN BOARD.BOARD_REPLY_LEV IS '답글단계';
COMMENT ON COLUMN BOARD.BOARD_REPLY_SEQ IS '답글순번';
COMMENT ON COLUMN BOARD.BOARD_READCOUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_DATE IS '작성날짜';


INSERT INTO MEMBER
VALUES('임');

INSERT INTO BOARD
VALUES (1, '임', '아아', 'ㅋㅋ', '임', '임', 1, 1, 1, 0, SYSDATE);

SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM USER_COL_COMMENTS;

--2
CREATE TABLE TB_BOOKS(
    ID VARCHAR(5) PRIMARY KEY,
    BOOKNAME VARCHAR2(50),
    BOOKPRICE NUMBER
);

CREATE SEQUENCE SEQID
START WITH 100
MAXVALUE 999
NOCYCLE
NOCACHE;

INSERT INTO TB_BOOKS
VALUES (SEQID.NEXTVAL, 'Java Programming', 30000);

SELECT SEQID.CURRVAL FROM DUAL;

--3번
CREATE TABLE testTbl(
id varchar2(10),
pass varchar2(30),
jno varchar2(30),
addr1 varchar(10),
addr2 varchar(10)
);

DROP TABLE TESTTBL;

ALTER TABLE TESTTBL
MODIFY ID NUMBER;

ALTER TABLE TESTTBL
MODIFY PASS VARCHAR2(30);

ALTER TABLE TESTTBL
MODIFY JNO VARCHAR2(30);

ALTER TABLE TESTTBL
MODIFY ADDR1 VARCHAR2(100);

ALTER TABLE TESTTBL
MODIFY ADDR2 VARCHAR2(100);

ALTER TABLE testTbl
ADD CONSTRAINT PK_TBID PRIMARY KEY(ID);

select * from user_constraints;
ALTER TABLE testTbl;

-- 4
CREATE TABLE MEMBERTB(
    ID VARCHAR2(10),
    PASS VARCHAR2(20),
    NAME VARCHAR2(10),
    AGE INT
);

INSERT INTO MEMBERTB
VALUES('0100', '1234', '이지은', 25);

INSERT INTO MEMBERTB
VALUES('0101', 'C33kimleechoi', '강한나', 30);

INSERT INTO MEMBERTB
VALUES('0102', 'SNSD', '서주현', 28);

SELECT * FROM MEMBERTB;