-- 문제 1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 1;

-- 문제 2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 문제 3
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (SUBSTR(STUDENT_ADDRESS, 1, 2) = '경기' OR SUBSTR(STUDENT_ADDRESS, 1, 2) = '강원')
AND SUBSTR(STUDENT_NO, 1, 2) <= '99'
ORDER BY 1;

-- 문제 4
-- ORABLE
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                          FROM TB_DEPARTMENT
                          WHERE DEPARTMENT_NAME = '법학과')
ORDER BY PROFESSOR_SSN ASC;          

-- ANSI
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR, TB_DEPARTMENT
WHERE TB_DEPARTMENT.DEPARTMENT_NO = TB_PROFESSOR.DEPARTMENT_NO
AND TB_DEPARTMENT.DEPARTMENT_NO = (SELECT TB_DEPARTMENT.DEPARTMENT_NO
                          FROM TB_DEPARTMENT
                          WHERE DEPARTMENT_NAME = '법학과')
ORDER BY PROFESSOR_SSN ASC;        

-- 문제 5
SELECT STUDENT_NO, TO_CHAR(ROUND(POINT, 2), '999.99') POINT
FROM TB_GRADE
WHERE (SUBSTR(TERM_NO, 1, 4) = '2004' AND SUBSTR(TERM_NO, 5, 2) = '02')
      AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

-- 문제 6
-- ORACLE
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

-- ANSI
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT, TB_DEPARTMENT
WHERE TB_DEPARTMENT.DEPARTMENT_NO = TB_STUDENT.DEPARTMENT_NO
ORDER BY STUDENT_NAME ASC;

-- 문제 7
-- ORACLE
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

-- ANSI
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS TC, TB_DEPARTMENT TD
WHERE TC.DEPARTMENT_NO = TD.DEPARTMENT_NO;

-- 문제 8
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO);

-- 문제 9
-- ORACLE
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- ANSI
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS TC, TB_PROFESSOR TP, TB_DEPARTMENT TD
WHERE TC.DEPARTMENT_NO = TP.DEPARTMENT_NO
AND TC.DEPARTMENT_NO = TD.DEPARTMENT_NO
AND CATEGORY = '인문사회';

-- 문제 10
-- ANSI
SELECT TS.STUDENT_NO 학번, STUDENT_NAME "학생 이름", TO_CHAR(AVG(POINT), '999.9') "전체 평점"
FROM TB_STUDENT TS, TB_GRADE TG, TB_DEPARTMENT TD
WHERE TS.STUDENT_NO = TG.STUDENT_NO
    AND TS.DEPARTMENT_NO = TD.DEPARTMENT_NO
    AND TD.DEPARTMENT_NO IN (SELECT TD.DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE TD.DEPARTMENT_NAME = '음악학과')
GROUP BY TS.STUDENT_NO, STUDENT_NAME, TG.STUDENT_NO
ORDER BY 1;
        
-- 문제 11 
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';
    
                        
-- 문제 12                        
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE SUBSTR(TERM_NO, 1, 4) = '2007'
    AND CLASS_NO = (SELECT CLASS_NO
                    FROM TB_CLASS
                    WHERE CLASS_NAME = '인간관계론')
ORDER BY 1;

-- 문제 13
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

-- 문제 14
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT, TB_PROFESSOR, TB_DEPARTMENT
WHERE TB_STUDENT.COACH_PROFESSOR_NO = TB_PROFESSOR.PROFESSOR_NO(+)
AND TB_DEPARTMENT.DEPARTMENT_NO = TB_STUDENT.DEPARTMENT_NO
AND TB_DEPARTMENT.DEPARTMENT_NO IN (SELECT TB_DEPARTMENT.DEPARTMENT_NO
                        FROM TB_DEPARTMENT
                        WHERE DEPARTMENT_NAME = '서반아어학과');

-- 문제 15
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", ROUND(AVG(POINT), 9) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;

-- 문제 16
SELECT CLASS_NO, CLASS_NAME, ROUND(AVG(POINT), 10) "AVG(POINT)"
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'                      
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;

-- 문제 17
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO IN (SELECT DEPARTMENT_NO
                        FROM TB_STUDENT
                        WHERE STUDENT_NAME = '최경희');

-- 문제 19
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT), 1) "전공평점"
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE CATEGORY IN (SELECT CATEGORY
                    FROM TB_DEPARTMENT
                    WHERE DEPARTMENT_NAME = '환경조경학과')
    
GROUP BY DEPARTMENT_NAME;








