-- DDL(ALTER, DROP)

-- [참고]
-- 데이터 딕셔너리
-- USER_CONSTRAINTS : 제약 조건 관리하는 데이터 딕셔너리
SELECT * FROM USER_CONSTRAINTS;

-- UESR_CONS_COLUMNS : 제약 조건을 컬럼별로 관리하는 데이터 딕셔너리
SELECT * FROM USER_CONS_COLUMNS;

-- USER_TABLES : 테이블을 관리하는 데이터 딕셔너리
SELECT * FROM USER_TABLES;

-- USER_TAB_COLS : 테이블의 컬럼을 관리하는 데이터 딕셔너리
SELECT * FROM USER_TAB_COLS;

-- 현재 KH 계정에 있는 테이블별 컬럼 수 조회
SELECT TABLE_NAME, COUNT(*)
FROM USER_TAB_COLS
GROUP BY TABLE_NAME;

----------------------------------------------------------------------------------
-- ALTER
-- 객체를 수정하는 구문

-- [표현식]
-- ALTER TABLE[개체] 테이블명 수정내용;

-- 수정할 내용
-- 컬럼 추가/삭제, 제약조건 추가/삭제
-- 컬럼 자료형 변경, DEFAULT값 변경
-- 테이블명 변경, 컬럼명, 제약조건 이름 변경

-- 1. 컬럼 추가, 수정 ,삭제
SELECT * FROM DEPT_COPY;

-- 컬럼 추가(ADD)
ALTER TABLE DEPT_COPY
ADD CNAME VARCHAR2(20);

SELECT * FROM DEPT_COPY;

-- 컬럼 추가 시 DEFAULT값 지정
ALTER TABLE DEPT_COPY
ADD LNAME VARCHAR2(40) DEFAULT '한국';

-- 컬럼 수정(MODIFY)

-- 컬럼 수정 전
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT, COLUMN_ID, COMMENTS
FROM USER_TAB_COLUMNS
JOIN USER_COL_COMMENTS USING(TABLE_NAME, COLUMN_NAME)
WHERE TABLE_NAME = 'DEPT_COPY';

ALTER TABLE DEPT_COPY
MODIFY DEPT_ID CHAR(3)
MODIFY DEPT_TITLE VARCHAR(30)
MODIFY LOCATION_ID VARCHAR2(2)
MODIFY CNAME CHAR(20)
MODIFY LNAME DEFAULT '미국';

-- 컬럼의 크기를 줄일 경우에는 기록된 값이 변경하려는 크기를 초과하는 값이 없을 때만 변경 가능
SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE VARCHAR2(10);

-- DEFAULT값 변경
ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE DEFAULT '한국';

INSERT INTO DEPT_COPY
VALUES('D11', '생산부', 'L2', NULL, DEFAULT);

SELECT * FROM DEPT_COPY;

-- 컬럼 삭제(DROP COLUMN || DROP (삭제할 컬럼명))
-- 데이터가 기록되어 있어도 삭제됨
-- 삭제된 컬럼은 복구 안됨
-- 테이블에는 최소 한 개의 컬럼이 존재해야 한다 : 모든 컬럼 삭제 불가
CREATE TABLE DEPT_COPY2
AS SELECT * FROM DEPT_COPY;

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT, COLUMN_ID, COMMENTS
FROM USER_TAB_COLUMNS
NATURAL JOIN USER_COL_COMMENTS
WHERE TABLE_NAME = 'DEPT_COPY2';

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_ID;

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_TITLE;

ALTER TABLE DEPT_COPY2
DROP COLUMN LOCATION_ID;

ALTER TABLE DEPT_COPY2
DROP COLUMN CNAME;

ALTER TABLE DEPT_COPY2
DROP COLUMN LNAME;
-- 테이블에 남아있는 컬럼이 하나뿐이므로 더 이상 삭제 불가. 

SELECT * FROM DEPT_COPY2;

ROLLBACK;  -- 롤백을 아무리 외쳐도 복구되지 않는다.

-- 제약조건이 설정되어 있는 컬럼 삭제
CREATE TABLE TB1(
    PK NUMBER PRIMARY KEY,
    FK NUMBER REFERENCES TB1,
    COL1 NUMBER,
    CHECK (PK > 0 AND COL1 > 0)
);

-- 테이블 제약조건 확인
SELECT *
FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME = 'TB1';

-- 컬럼 삭제 시 참조하고 있는 컬럼이 있다면 삭제 불가능
ALTER TABLE TB1
DROP COLUMN PK;

-- 제약조건과 함께 삭제(CASCADE CONSTRAINTS)
ALTER TABLE TB1
DROP COLUMN PK CASCADE CONSTRAINTS;

SELECT * FROM TB1;

SELECT * FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME = 'TB1';

-------------------------------------ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
-- 2. 제약조건 추가, 삭제
-- 제약조건 추가(ADD CONSTRAINT 제약조건명 제약조건(컬럼명))
-- 단, NOT NULL 제약조건 추가는 ADD가 아닌 MODIFY로 추가
-- MODIFY 컬럼명 CONSTRAINT 제약조건명 NOT NULL

SELECT *
FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME = 'DEPT_COPY';
--> DEPARTMENT의 NOT NULL 조건만 복사되어 있음

-- PRIMARY KEY 추가
ALTER TABLE DEPT_COPY
ADD CONSTRAINT DCOPY_DID_PH PRIMARY KEY(DEPT_ID);

-- UNIQUE 추가
ALTER TABLE DEPT_COPY
ADD CONSTRAINT DCOPY_DTITLE_UNQ UNIQUE(DEPT_TITLE);

-- NOT NULL
ALTER TABLE DEPT_COPY
MODIFY LNAME CONSTRAINT DCOPY_LNAME_NN NOT NULL;

-- 추가된 제약 조건 확인
SELECT *
FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME  = 'DEPT_COPY';

-- 제약조건 삭제(DROP CONSTRAINT 제약조건명)
ALTER TABLE DEPT_COPY
DROP CONSTRAINT DCOPY_DID_PH;

-- 제약조건 여러개 삭제
ALTER TABLE DEPT_COPY
DROP CONSTRAINT DCOPY_DTITLE_UNQ
DROP CONSTRAINT SYS_C007145;

-- NOT NULL 제약조건은 추가와 같이 MODIFY를 통해 수정
ALTER TABLE DEPT_COPY
MODIFY LOCATION_ID NULL;

-- 제약조건 삭제 확인
SELECT *
FROM USER_CONSTRAINTS C1
JOIN USER_CONS_COLUMNS C2 USING(CONSTRAINT_NAME)
WHERE C1.TABLE_NAME  = 'DEPT_COPY';

--------------------------------------------------------------------------------------------------------------------
-- 3. 컬럼, 제약조건, 테이블 이름 변경
-- 컬럼이름 변경(RENAME COLUMN 컬럼명 TO 변경명)
ALTER TABLE DEPT_COPY
RENAME COLUMN DEPT_TITLE TO DEPT_NAME;

SELECT * FROM DEPT_COPY;

-- 제약조건 이름 변경(RENAME CONSTRAINT 제약조건명 TO 변경명)

-- 변경 전 USER_ForeignKEY 테이블 제약 조건
SELECT UC.CONSTRAINT_NAME 이름, UC.CONSTRAINT_TYPE 유형, UCC.COLUMN_NAME 컬럼명,
       UC.R_CONSTRAINT_NAME 참조, UC.DELETE_RULE 삭제규칙
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON(UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'USER_FOREIGNKEY';

-- 제약조건명이 없는 NOT NULL 제약 조건명 변경
ALTER TABLE USER_FOREIGNKEY
RENAME CONSTRAINT SYS_C007087 TO UF_USERPWD_NN;

-- 기존 FOREIGN KE 제약조건명 변경
ALTER TABLE USER_FOREIGNKEY
RENAME CONSTRAINT FK_GRADE_CODE TO UF_GRADECODE_FK;

-- 테이블명 변경(RNAME [테이블명] TO 변경명)
ALTER TABLE DEPT_COPY
RENAME TO DEPT_TEST;

SELECT * FROM DEPT_COPY;
-- 테이블명이 변경되어 조회 불가능

SELECT * FROM DEPT_TEST;
----------------------------------------------------------------------------------------------------------------
-- 4. 테이블 삭제
DROP TABLE DEPT_TEST
CASCADE CONSTRAINTS; -- 제약 조건도 함께 삭제
-- ALTER ~ DROP, DROP~ 두 개

-- DELETE : DML, ROLLBACK 가능
-- TRUNCATE : DDL, ROLLBACK 불가능
-- DROP TABLE : DDL, ROLLBACK 불가능