-- SYNONYM (SYSTEM)
-- 1) SAMPLE 계정에 KH계정의 EMPLOYEE 테이블을 SELECT 할 수 있는 권한 부여
GRANT SELECT
ON kh.EMPLOYEE TO SAMPLE;

-- SELECT 계정에 SYNONYM 생성 권한 부여
GRANT CREATE SYNONYM TO SAMPLE;

-- 공개 동의어 만들기
CREATE PUBLIC SYNONYM DEPT
FOR kh.DEPARTMENT;

SELECT * FROM kh.DEPARTMENT;

SELECT * FROM DEPT;

-- 공개 SYNONYM으로 되어있어도 권한을 받아야 사용 가능
GRANT SELECT ON DEPT TO SAMPLE;

-- 3. SYNONYM 삭제
DROP PUBLIC SYNONYM DEPT;