-- 1번
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 1
);

-- 2번
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);
-- 3번
ALTER TABLE TB_CATEGORY
ADD PRIMARY KEY(NAME);

-- 4번
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

-- 5번
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10);

-- 6번
ALTER TABLE TB_CATEGORY 
RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CATEGORY 
RENAME COLUMN USE_YN TO CATEGORY_USE_YN;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO TB_CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO TB_CLASS_TYPE_NAME;

-- 7번
-- 조회
SELECT UC.CONSTRAINT_NAME 이름, UC.CONSTRAINT_TYPE 유형, UCC.COLUMN_NAME 컬럼명,
       UC.R_CONSTRAINT_NAME 참조, UC.DELETE_RULE 삭제규칙
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON(UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'TB_CATEGORY';

SELECT UC.CONSTRAINT_NAME 이름, UC.CONSTRAINT_TYPE 유형, UCC.COLUMN_NAME 컬럼명,
       UC.R_CONSTRAINT_NAME 참조, UC.DELETE_RULE 삭제규칙
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON(UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'TB_CLASS_TYPE';

-- 변경
ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT SYS_C007146 TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007145 TO PK_TB_CLASS_TYPE_NO;

-- 8번
INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
COMMIT;

-- 9번
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

SELECT UC.CONSTRAINT_NAME 이름, UC.CONSTRAINT_TYPE 유형, UCC.COLUMN_NAME 컬럼명,
       UC.R_CONSTRAINT_NAME 참조, UC.DELETE_RULE 삭제규칙
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON(UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'TB_DEPARTMENT';



-- 10번
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_학생일반정보;
   
-- 11번
CREATE OR REPLACE VIEW VW_지도면담
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
   FROM TB_STUDENT
   LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
   JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
   ORDER BY DEPARTMENT_NAME;

SELECT * FROM VW_지도면담;

-- 12번
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NAME) STUDENT_COUNT
   FROM VW_지도면담
   GROUP BY DEPARTMENT_NAME;
   
SELECT * FROM VW_학과별학생수;

-- 13번
UPDATE VW_학생일반정보
SET STUDENT_NAME = '임세웅'
WHERE STUDENT_NO = 'A213046';

SELECT * FROM VW_학생일반정보;

-- 14번
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_학생일반정보
   WITH READ ONLY;
   























