-- 1번
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME VARCHAR(30);

INSERT INTO TB_CLASS_TYPE (NO, NAME)
VALUES (01, '전공필수');

INSERT INTO TB_CLASS_TYPE (NO, NAME)
VALUES (02, '전공선택');

INSERT INTO TB_CLASS_TYPE (NO, NAME)
VALUES (03, '교양필수');

INSERT INTO TB_CLASS_TYPE (NO, NAME)
VALUES (04, '교양선택');

INSERT INTO TB_CLASS_TYPE (NO, NAME)
VALUES (05, '논문지도');

SELECT * FROM TB_CLASS_TYPE;

-- 2번
CREATE TABLE TB_학생일반정보 (
    STUDENT_NO VARCHAR2(10),
    STUDENT_NAME VARCHAR2(40),
    STUDENT_ADDRESS VARCHAR2(200)
);

INSERT INTO TB_학생일반정보 (
    SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT
);

SELECT * FROM TB_학생일반정보;

-- 3번
CREATE TABLE TB_국어국문학과(
    STUDENT_NO VARCHAR2(10),
    STUDENT_NAME VARCHAR2(40),
    STUDENT_BIRTH VARCHAR(10),
    COACH_NAME VARCHAR(30)
);

INSERT INTO TB_국어국문학과 (
    SELECT STUDENT_NO, STUDENT_NAME, 19 ||  SUBSTR(STUDENT_SSN, 1, 2), PROFESSOR_NAME
    FROM TB_STUDENT
    LEFT JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
    LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과'
);

-- DELETE FROM TB_국어국문학과;

SELECT * FROM TB_국어국문학과;

-- 4번
UPDATE TB_DEPARTMENT
SET CAPACITY = FLOOR(CAPACITY * 1.1);

-- 5번
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

-- 6번
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

-- 7번

-- 조회용 SELECT문
SELECT STUDENT_NAME, CLASS_NAME, POINT
FROM TB_STUDENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE STUDENT_NAME = '김명훈'
AND TERM_NO = 200501
AND CLASS_NAME = '피부생리학';

-- 풀이
UPDATE TB_GRADE
SET POINT = 3.5
WHERE TERM_NO = 200501
AND STUDENT_NO = (SELECT STUDENT_NO
                  FROM TB_STUDENT
                  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                  WHERE STUDENT_NAME = '김명훈'
                  AND DEPARTMENT_NAME = '의학과')
AND CLASS_NO = (SELECT CLASS_NO
                FROM TB_CLASS
                WHERE CLASS_NAME = '피부생리학');
                
-- 8번
DELETE FROM TB_GRADE
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                     FROM TB_STUDENT
                     WHERE ABSENCE_YN = 'Y');


